### ISSUE TITLE
Initiation Documentation 

### ISSUE THREAD

**Issue by fardeenmohd** [fardeenmohd/Chess-Masters#2]
- A short Documentation of project(Electronic version, Description of problem, An analysis, Some existing solutions ,Description of preffered solutions , some implementation problem, simulation results from application).

**Comment by matrackif** [comment]
I uploaded the first MS Word file to our root git directory, there are guaranteed mistakes and maybe misunderstandings so please take a look.

**Comment by fardeenmohd** [comment]
The initial documentation is pretty much finalised(Formatted and Structured) but feel free to add somethings in the description part related to our research and opinions.close this issue when you pass it.
