### ISSUE TITLE
Implement pieces

### ISSUE THREAD

**Issue by IvanMatyazh** [fardeenmohd/Chess-Masters#4]
1. Derive them from the base class and override method GetPossibleMoves().
2. Use BasePiece methods in order to achieve this
3. Use the constant in the BasePiece class in order to specify the moveLength (in case its not equal to 1)

**Comment by fardeenmohd** [comment]
Each type of piece must be a different class or shall we just make one for piece and identify them via some class member?

**Comment by IvanMatyazh** [comment]
I thought about different classes (like Knight and King classes have different implementation). Btw, how do you want to achieve different behaviours of the pieces by making one class for piece and identify it with some class member? I can't imagine this code in my mind. Please, describe it in details.

**Comment by fardeenmohd** [comment]
I just wanted to get the idea how you made the base piece class. so different classes is the way you thought about it.
