### ISSUE TITLE
Implement interface for user moves

### ISSUE THREAD

**Issue by IvanMatyazh** [fardeenmohd/Chess-Masters#9]
1. Make a system responsive to the user actions.
2. Modify ChessMaster project, especially Click command on each cell.

**Comment by fardeenmohd** [comment]
I added some basic movements, just need a lil polishing for quick piece switching and possible move logic ,
all the new pieces implementation and movement is in the pieceImplementation branch

**Comment by fardeenmohd** [comment]
all done except collision detection for getpossiblemoves() to see if any other pieces are in its way
